0xPolygon/zkevm-data-streamer

tool/db/db.go, tool/db/types.go, tool/main.go
=> follow spec

Makefile, cmd/main.go
Add the option to run the client using make.
- @dpunish3r
=> launch server or client

cmd/main.go, log/log.go
=> fix logger

cmd/main.go, tool/db/db.go, tool/db/types.go, tool/main.go
=> change time.Time to int64

datastreamer/entities.go, log/log.go, tool/config/tool.config.toml, tool/db/types.go
=> entities refactor

datastreamer/entities.go, datastreamer/entities_test.go, go.mod, tool/db/db.go, tool/db/types.go, tool/db/types_test.go
=> Add encode tests

README.md
Add blockHash and stateRoot to L2 Block entry. Remove batchNum from L2 TX.
@ToniRamirezM 
@dpunish3r 
@agnusmor
=> Add blockHash and stateRoot entry. Remove batchNum from L2 TX.

cmd/main.go, tool/db/db.go, tool/db/types.go, tool/db/types_test.go, tool/main.go
=> Add close block entity

.golangci.yml, cmd/main.go, datastreamer/config.go, datastreamer/entities.go, datastreamer/streamclient.go, datastreamer/streamfile.go, datastreamer/streamserver.go, tool/config/config.go, tool/db/config.go, tool/db/db.go, tool/main.go
=> add linter rules

README.md
Added block num to the endBlock Event.
Change type of hashes (stat roots) from u32 to u256
=> Update endBlock Event

tool/db/db.go, tool/db/types.go, tool/main.go
resume generation of the stream file in tool
=> resume generation

tool/db/db.go
sets 0 as forkid for genesis block
=> set 0 as forkid for genesis block

datastreamer/entities.go, datastreamer/entities_test.go, go.mod, go.sum
Fixes entity toString and enables its test
- @agnusmor 
- @dpunish3r
=> fix entity toString and test

log/log.go
Fixes fatalf logger
- @agnusmor 
- @dpunish3r
=> fixe fatalf logger

README.md, datastreamer/streamfile.go
- Bug fix locating entry
- README updated
=> Bug fix edge case locating entry

datastreamer/datastreamer_test.go, datastreamer/streamclient.go, datastreamer/streamserver.go
Handles entity not found errors during command entity or bookmark requests.
- @dpunish3r 
- @agnusmor
=> Do not hang request on entity not found

cmd/main.go, datastreamer/streamfile.go, datastreamer/streamserver.go, relay/main.go
- Improve processing performance
=> Improve processing performance

datastreamer/streamserver.go
- Reduce log level of a record
=> Reduce log level of a record

README.md, cmd/main.go
- Update README. 
- Add sanitycheck option in dsapp client
=> Update README. Add sanitycheck option in dsapp client

README.md
Adds new fields to the sequencer data stream use case:
- InfoRoot
- LblockHash
=> Updates for etrog

README.md
removes l1 info root from use case
- @dpunish3r 
- @agnusmor 
-
=> remove l1 info root from use case

cmd/main.go
Add batch boomark in datastream demo app
=> add batch boomark

cmd/main.go, datastreamer/datastreamer_test.go
=> Add dump batch tool in dsapp

README.md, cmd/main.go, datastreamer/datastreamer_test.go, datastreamer/streambookmark.go, datastreamer/streamclient.go, datastreamer/streamrelay.go
Improve the client API, making it more user-friendly. The generic command and client attributes for passing parameters and receiving responses have been removed. Now there are specific commands, each with its parameters and response.
API removed:
- ExecCommand()
API added:
- ExecCommandStart(fromEntry)
- ExecCommandStartBookmark(fromBookmark)
- ExecCommandStop()
- ExecCommandGetHeader() -> HeaderEntry
- ExecCommandGetEntry(fromEntry) -> FileEntry
- ExecCommandGetBookmark(fromBookmark) -> FileEntry
@agnusmor 
@ToniRamirezM
=> improve stream client API

datastreamer/streamclient.go
Adds new constructor for client with log config as parameter
- @agnusmor 
- @dpunish3r
=> Add new constructor for client with log config as parameter

datastreamer/streamfile.go
file entry public encoder
- @agnusmor 
- @dpunish3r
=> file entry public encoder

cmd/main.go, datastreamer/config.go, datastreamer/datastreamer_test.go, datastreamer/streamfile.go, datastreamer/streamrelay.go, datastreamer/streamserver.go, relay/main.go
- Add timeout for write operations on client connections
- Organize some logs
@agnusmor 
@ToniRamirezM
=> Add timeout for write operations on client connections

cmd/main.go, datastreamer/config.go, datastreamer/datastreamer_test.go, datastreamer/streamrelay.go, datastreamer/streamserver.go, relay/main.go
Closes inactive client connections that reached the inactivity timeout.
@ToniRamirezM
=> Close inactive client connections

.golangci.yml, Makefile, cmd/main.go, datastreamer/config.go, datastreamer/datastreamer_test.go, datastreamer/streambookmark.go, datastreamer/streamclient.go, datastreamer/streamfile.go, datastreamer/streamrelay.go, datastreamer/streamserver.go, log/config.go, log/log.go, log/log_test.go, relay/main.go
Closes #122.
Introduce more linting rules and fix the current violations in the codebase.
=> Introduce more rules to the linter configuration

datastreamer/streamserver.go
Refactor logs that are showed when the library is used from the legacy sequencer
@joanestebanr
=> Refactor logs

.github/workflows/test.yml, Dockerfile, Makefile, cmd/main.go, datastreamer/streamserver.go, log/log_test.go, sonar-project.properties
Closes https://github.com/0xPolygon/zkevm-data-streamer/issues/127.
What does this PR do?
The PR includes code coverage report with the SonarCloud and also fixes a couple of existing issues.
=> Introduce SonarCloud with code coverage

datastreamer/streamclient.go
Adds functions to:
- Check if the client is started
- Reset the process callback function
=> reset process func and isStarted

datastreamer/streambookmark.go, datastreamer/streamclient.go, datastreamer/streamfile.go, datastreamer/streamserver.go
=> feat: review logs level

datastreamer/streamserver.go
Closes #<issue number>.
Check the client for nil before processing the command. Cdk-erigon had a panic here.
- @-John
- @-Doe
Codeowner reviewers:
- @-Alice
- @-Bob
=> fix(safe-client): check safe client for nil
